--- !ruby/object:PostBuilder
post_id: 1
title: Resolution
tags: stuff
author: Clare Lennon
featured: true
summary: I started my New Year’s Resolution in December. Get fit before the holiday food, you know?
long_read: false
post_date: 2014-02-07
link: "post/resolution"
partial: "partials/posts/new_years_resolution"

--- !ruby/object:PostBuilder
post_id: 2
title: The time I had to huddle with 13-year-olds to make it through
tags:
author:
featured: true
summary:
long_read:
post_date: 2013-10-11
link: "post/haunted_house"
partial: "partials/posts/test_post"

--- !ruby/object:PostBuilder
post_id: 3
title: On reading
tags:
author: Clare Lennon
featured: false
summary: A commitment to read more
long_read: false
post_date: 2014-02-23
link: 'post/on_reading'
partial: 'partials/posts/on_reading'
